import { shuffle } from "lodash";
import { Anime } from "@/lib/types";
import type { Metadata } from "next";
import createApolloClient from "@/lib/apollo.client";
import { Geist, Geist_Mono } from "next/font/google";
import { GET_HERO_SECTION_ANIMES } from "@/lib/queries";

import { HeroBanner } from "../components/Banners/HeroBanner";

import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { Sidebar } from "../components/domains/home/Sidebar";
import { useToast } from "@/hooks/useToast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createApolloClient();

  const { data, error, loading } = await client.query({
    query: GET_HERO_SECTION_ANIMES,
  });

  const getHeroAnimes = () => {
    return loading
      ? []
      : data
      ? shuffle(
          data.Page.media.filter(
            (anime: Anime) =>
              anime.bannerImage != null && anime.description.length
          )
        ).slice(0, 3)
      : [];
  };

  return (
    <div className="antialiased h-full flex flex-col bg-gray-100 relative">
      <ScrollArea className="w-full h-full bg-black">
        <div className="sm:min-h-96 -mt-2 sm:-mt-16">
          <HeroBanner
            animes={getHeroAnimes()}
            isLoading={loading}
            error={!!error}
          />
        </div>

        <div className="flex-grow">
          <div className="grid md:grid-cols-[1.4fr_6fr] h-full bg-yellow-300">
            <Sidebar />
            <main className="bg-black md:w-full px-4 md:px-0 h-full overflow-x-hidden ">
              {children}
            </main>
          </div>
        </div>
        <ScrollBar orientation="vertical" />
      </ScrollArea>
    </div>
  );
}
