"use client";
import type { Metadata } from "next";
import { data } from "@/data/main.json";
import { AnimeProps } from "@/app/(routes)/home/page";
import { Geist, Geist_Mono } from "next/font/google";
import { HomeBanner } from "../components/Banners";
import StarSelector from "../components/domains/home/StarSelector";
import GenereSelector from "../components/domains/home/GenereSelector";
import StatusSelector from "../components/domains/home/StatusSelector";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mockData: AnimeProps[] = data.Page.media;

  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col bg-gray-100 relative`}
    >
      <Header />
      <HomeBanner anime={mockData[0]} />
      <div className="flex-grow">
        <div className="grid grid-cols-[1.5fr_6fr] h-full bg-blue-300">
          <Sidebar />
          <main className="bg-black w-full overflow-x-hidden ">{children}</main>
        </div>
      </div>
      <footer className="h-12 p-4 w-full bg-black flex justify-center border-t-4 border-blue-500">
        Made with ❤️ by Daniel Kcomt :D
      </footer>
    </div>
  );
}

function Sidebar() {
  return (
    <aside className="bg-gray-700 w-full h-full flex flex-col pt-10 px-3 gap-3">
      <span className="text-2xl font-semibold pt-6 pb-2">Busqueda</span>
      <input placeholder="Búsqueda" />

      <span className="text-2xl font-semibold pt-6 pb-2">Filtros</span>

      <StarSelector
        onSelectStar={(value) => {
          console.log(value);
        }}
      />

      <GenereSelector
        onSelectGenere={(value) => console.log("GENERE SELECTED : " + value)}
      />

      <StatusSelector
        onSelectStatus={(value) => console.log("GENERE SELECTED : " + value)}
      />
    </aside>
  );
}
