"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { SkeletonRectangle } from "../components/SkeletonRectangle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black flex flex-col relative h-full`}
    >
      {children}
    </div>
  );
}
