import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloProvider from "@/app/utils/ApolloProvider";
import { ThemeProvider } from "next-themes";
import Header from "./components/Header";
import { Text } from "./components/Typography";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ApolloProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen grid grid-rows-[4rem_1fr_3rem] relative w-scr max-w-full`}
            >
              <div className="w-full h-16">
                <Header />
              </div>

              <main className="w-full h-full overflow-x-hidden">
                {children}
              </main>

              <footer className="h-full p-4 w-full flex justify-center bg-yellow-400">
                <Text.Bold size="base" className="text-black">
                  Made with ❤️ by Daniel Kcomt :D
                </Text.Bold>
              </footer>
            </body>
          </ThemeProvider>
        </ApolloProvider>
      </html>
    </ClerkProvider>
  );
}
